# Overview

ModelSkill compares model results with observations. The workflow can be split in two phases:

1. **Matching** - making sure that observations and model results are in the same space and time
2. **Analysis** - plots and statistics of the matched data

If the observations and model results are already matched (i.e. are stored in the same data source), 
the [`from_matched()`](`modelskill.from_matched`) function can be used to go directly to the analysis phase. 
If not, the [`match()`](`modelskill.match`) function can be used to match the observations and model results in space and time.


## Matching

If the observations and model results are not in the same data source (e.g. dfs0 file), 
they will need to be defined and then matched in space and time with the `match()` function. 


### Define observations

The observations can be defined as a [`PointObservation`](`modelskill.PointObservation`), a [`TrackObservation`](`modelskill.TrackObservation`) (a moving point) or a [`VerticalObservation`](`modelskill.VerticalObservation`) (a depth profile at a fixed position).

```{python}
import modelskill as ms
o1 = ms.PointObservation("../data/obs.dfs0", item="obs_WL",x=366844.15, y=6154291.6)
```

The `item` needs to be specified as either the item number or the item name if the input file contains multiple items. Several other parameters can be specified, such as the name of the observation, the x- and y-position, and the quantity type and unit of the observation. 


### Define model results

A model result will either be a simple point/track like the observations, or spatial field (e.g. 2d dfsu file) from which the model results will be *extracted* at the observation positions. The following types are available:

* [`PointModelResult`](`modelskill.PointModelResult`) - a point result from a dfs0/nc file or a DataFrame
* [`TrackModelResult`](`modelskill.TrackModelResult`) - a track result from a dfs0/nc file or a DataFrame
* [`VerticalModelResult`](`modelskill.VerticalModelResult`) - a depth profile from a dfs0 file or a DataFrame
* [`GridModelResult`](`modelskill.GridModelResult`) - a spatial field from a dfs2/nc file or a Xarray Dataset
* [`DfsuModelResult`](`modelskill.DfsuModelResult`) - a spatial field from a dfsu file (2D or 3D)

```{python}
mr1 = ms.PointModelResult("../data/model.dfs0", item="WL")
```

### Match observations and model results

The `match()` function will interpolate the model results to the time (and space) of the observations and return a collection of `Comparer` objects that can be used for analysis. 

```{python}
cc = ms.match(o1, mr1)
cc
```


## Vertical profiles

Model results can also be validated against vertical profiles, e.g. CTD casts of
salinity or temperature. The observation is a
[`VerticalObservation`](`modelskill.VerticalObservation`) and the model result is either a
[`VerticalModelResult`](`modelskill.VerticalModelResult`) (a pre-extracted column) or a
3D [`DfsuModelResult`](`modelskill.DfsuModelResult`), from which the column at the
observation position is *extracted* automatically (see [matching](matching.qmd)).

The result is an ordinary [`Comparer`](`modelskill.Comparer`) with `gtype="vertical"`,
so `cmp.skill()` and all the usual plots work as before. In addition, a `vertical`
accessor gives access to depth-aware skill and plots (see [plotting](plotting.qmd)).
The comparer can be sliced by depth with `cmp.sel(z=-2)` or `cmp.sel(z=slice(-10, 0))`
(see [selecting data](selecting-data.qmd)), and the profile can be collapsed to a
single value per timestep with `cmp.vertical.mean()`, `.min()` or `.max()` (which
return point comparers).


## Analysis

Once the observations and model results are matched, the `Comparer` object can be used for analysis and plotting. 

