# Comparer.skill { #modelskill.Comparer.skill }

`Comparer.skill(by=None, metrics=None, **kwargs)`

Skill assessment of model(s)

## Parameters

| Name      | Type                      | Description                                                                                                                                                                                                                                                                                                                                                                                    | Default   |
|-----------|---------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `by`      | str or typing.List\[str\] | group by, by default ["model"]  - by column name - by temporal bin of the DateTimeIndex via the freq-argument (using pandas pd.Grouper(freq)), e.g.: 'freq:M' = monthly; 'freq:D' daily - by the dt accessor of the DateTimeIndex (e.g. 'dt.month') using the syntax 'dt:month'. The dt-argument is different from the freq-argument in that it gives month-of-year rather than month-of-data. | `None`    |
| `metrics` | list                      | list of modelskill.metrics, by default modelskill.options.metrics.list                                                                                                                                                                                                                                                                                                                         | `None`    |

## Returns

| Type                        | Description             |
|-----------------------------|-------------------------|
| modelskill.skill.SkillTable | skill assessment object |

## See Also

sel
    a method for filtering/selecting data

## Examples

```python
>>> import modelskill as ms
>>> cc = ms.match(c2, mod)
>>> cc['c2'].skill().round(2)
               n  bias  rmse  urmse   mae    cc    si    r2
observation
c2           113 -0.00  0.35   0.35  0.29  0.97  0.12  0.99
```

```python
>>> cc['c2'].skill(by='freq:D').round(2)
             n  bias  rmse  urmse   mae    cc    si    r2
2017-10-27  72 -0.19  0.31   0.25  0.26  0.48  0.12  0.98
2017-10-28   0   NaN   NaN    NaN   NaN   NaN   NaN   NaN
2017-10-29  41  0.33  0.41   0.25  0.36  0.96  0.06  0.99
```