# TrackModelResult { #modelskill.TrackModelResult }

`TrackModelResult(self, data, *, name=None, item=None, quantity=None, x_item=0, y_item=1, keep_duplicates='first', aux_items=None)`

Construct a TrackModelResult from a dfs0 file,
mikeio.Dataset, pandas.DataFrame or a xarray.Datasets

## Parameters

| Name              | Type                                        | Description                                                                                                                                                                                                                                                  | Default    |
|-------------------|---------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `data`            | modelskill.types.modelskill.types.TrackType | The input data or file path                                                                                                                                                                                                                                  | _required_ |
| `name`            | typing.Optional\[str\]                      | The name of the model result, by default None (will be set to file name or item name)                                                                                                                                                                        | `None`     |
| `item`            | str \| int \| None                          | If multiple items/arrays are present in the input an item must be given (as either an index or a string), by default None                                                                                                                                    | `None`     |
| `x_item`          | str \| int \| None                          | Item of the first coordinate of positions, by default None                                                                                                                                                                                                   | `0`        |
| `y_item`          | str \| int \| None                          | Item of the second coordinate of positions, by default None                                                                                                                                                                                                  | `1`        |
| `quantity`        | modelskill.quantity.Quantity                | Model quantity, for MIKE files this is inferred from the EUM information                                                                                                                                                                                     | `None`     |
| `keep_duplicates` | (str, bool)                                 | Strategy for handling duplicate timestamps (wraps xarray.Dataset.drop_duplicates) "first" to keep first occurrence, "last" to keep last occurrence, False to drop all duplicates, "offset" to add milliseconds to consecutive duplicates, by default "first" | `'first'`  |
| `aux_items`       | typing.Optional\[list\[int \| str\]\]       | Auxiliary items, by default None                                                                                                                                                                                                                             | `None`     |