# Function reference {.doc .doc-index}

## Observation

Observation classes and functions

| | |
| --- | --- |
| [observation](observation.qmd#modelskill.observation) | A factory function for creating an appropriate observation object |
| [PointObservation](PointObservation.qmd#modelskill.PointObservation) | Class for observations of fixed locations |
| [TrackObservation](TrackObservation.qmd#modelskill.TrackObservation) | Class for observation with locations moving in space, e.g. satellite altimetry |

## Model Result

Model result classes and functions

| | |
| --- | --- |
| [model_result](model_result.qmd#modelskill.model_result) | A factory function for creating an appropriate object based on the data input. |
| [PointModelResult](PointModelResult.qmd#modelskill.PointModelResult) | Construct a PointModelResult from a 0d data source: |
| [TrackModelResult](TrackModelResult.qmd#modelskill.TrackModelResult) | Construct a TrackModelResult from a dfs0 file, |
| [DfsuModelResult](DfsuModelResult.qmd#modelskill.DfsuModelResult) | Construct a DfsuModelResult from a dfsu file or mikeio.Dataset/DataArray. |
| [GridModelResult](GridModelResult.qmd#modelskill.GridModelResult) | Construct a GridModelResult from a file or xarray.Dataset. |
| [DummyModelResult](DummyModelResult.qmd#modelskill.DummyModelResult) |  |

## Matching

Matching classes and functions

| | |
| --- | --- |
| [matching](matching.qmd#modelskill.matching) |  |

## Comparer

Comparer classes and functions

| | |
| --- | --- |
| [Comparer](Comparer.qmd#modelskill.Comparer) | Comparer class for comparing model and observation data. |
| [ComparerCollection](ComparerCollection.qmd#modelskill.ComparerCollection) | Collection of comparers, constructed by calling the `modelskill.match` |

## Metrics

Metrics classes and functions

| | |
| --- | --- |
| [metrics](metrics.qmd#modelskill.metrics) | The `metrics` module contains different skill metrics for evaluating the  |