# PointObservation { #modelskill.PointObservation }

`PointObservation(self, data, *, item=None, x=None, y=None, z=None, name=None, weight=1.0, quantity=None, aux_items=None, attrs=None)`

Class for observations of fixed locations

Create a PointObservation from a dfs0 file or a pd.DataFrame.

## Parameters

| Name        | Type                                                                                                                                                                 | Description                                                                                                                     | Default    |
|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|------------|
| `data`      | (str, pathlib.Path, mikeio.mikeio.Dataset, mikeio.mikeio.DataArray, pandas.pandas.DataFrame, pandas.pandas.Series, xarray.xarray.Dataset or xarray.xarray.DataArray) | filename (.dfs0 or .nc) or object with the data                                                                                 | _required_ |
| `item`      | (int, str)                                                                                                                                                           | index or name of the wanted item/column, by default None if data contains more than one item, item must be given                | `None`     |
| `x`         | float                                                                                                                                                                | x-coordinate of the observation point, inferred from data if not given, else None                                               | `None`     |
| `y`         | float                                                                                                                                                                | y-coordinate of the observation point, inferred from data if not given, else None                                               | `None`     |
| `z`         | float                                                                                                                                                                | z-coordinate of the observation point, inferred from data if not given, else None                                               | `None`     |
| `name`      | str                                                                                                                                                                  | user-defined name for easy identification in plots etc, by default file basename                                                | `None`     |
| `quantity`  | modelskill.Quantity                                                                                                                                                  | The quantity of the observation, for validation with model results For MIKE dfs files this is inferred from the EUM information | `None`     |
| `aux_items` | list                                                                                                                                                                 | list of names or indices of auxiliary items, by default None                                                                    | `None`     |
| `attrs`     | dict                                                                                                                                                                 | additional attributes to be added to the data, by default None                                                                  | `None`     |
| `weight`    | float                                                                                                                                                                | weighting factor for skill scores, by default 1.0                                                                               | `1.0`      |

## Examples

```python
>>> import modelskill as ms
>>> o1 = ms.PointObservation("klagshamn.dfs0", item=0, x=366844, y=6154291, name="Klagshamn")
>>> o2 = ms.PointObservation("klagshamn.dfs0", item="Water Level", x=366844, y=6154291)
>>> o3 = ms.PointObservation(df, item=0, x=366844, y=6154291, name="Klagshamn")
>>> o4 = ms.PointObservation(df["Water Level"], x=366844, y=6154291)
```